# The URL the site will be built for
base_url = "https://unplannedobsolescence.com"

compile_sass = false

title = "Unplanned Obsolescence"
description = "A blog about trying to write software that doesn't rot"
author = "Alexander Petros"

generate_feeds = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
smart_punctuation = true
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
# Put all your custom variables here
